### ISSUE TITLE
TypeError: 'Game' object is not subscriptable

### ISSUE THREAD

**Issue by davidindub** [davidindub/quiz-master#17]

**Comment by davidindub** [comment]
```python
Traceback (most recent call last):
  File "run.py", line 140, in <module>
    main()
  File "run.py", line 122, in main
    create_form.create_form_body(google_quiz)
  File "/workspace/quiz-master/create_form.py", line 51, in create_form_body
    form_questions = create_gform_game(game_obj)
  File "/workspace/quiz-master/create_gform_items.py", line 226, in create_gform_game
    rounds = game_obj["rounds"]
TypeError: 'Game' object is not subscriptable
```

**Comment by davidindub** [comment]
Fixed by using dot notation to access Class object and `.__dict__` method where needed
