### ISSUE TITLE
Bug: FileNotFoundError in Heroku build

### ISSUE THREAD

**Issue by davidindub** [davidindub/quiz-master#21]

**Comment by davidindub** [comment]
```python
Running startup command: python3 run.py

Traceback (most recent call last):
  File "/app/run.py", line 10, in <module>
    import create_form
  File "/app/create_form.py", line 14, in <module>
    CREDS = service_account.Credentials.from_service_account_file(
  File "/app/.heroku/python/lib/python3.10/site-packages/google/oauth2/service_account.py", line 238, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/app/.heroku/python/lib/python3.10/site-packages/google/auth/_service_account_info.py", line 72, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'client_secrets.json'
```

**Comment by davidindub** [comment]
- Renamed variable
- Deleted and re-added config vars in heroku
- Renamed credentials.json to creds.json ✅
